apiVersion: v1
kind: Service
metadata:
  name: ecommconfig
  labels:
    app: ecommconfig
spec:
  clusterIP: None
  ports:
    - port: 8090
      name: ecommconfig
  selector:
    app: ecommconfig

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecommconfig
spec:
  serviceName: "ecommconfig"
  replicas: 1
  selector:
    matchLabels:
      app: ecommconfig
  template:
    metadata:
      labels:
        app: ecommconfig
    spec:
      containers:
        - name: ecommconfig
          image: jeffinjude/ecomm-config-server:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8090

---                  

apiVersion: v1
kind: Service
metadata:
  name: ecommconfig-lb
  labels:
    app: ecommconfig
spec:
  selector:
    app: ecommconfig
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
