apiVersion: v1
kind: Service
metadata:
  name: ecommeureka
  labels:
    app: ecommeureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: ecommeureka
  selector:
    app: ecommeureka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecommeureka
spec:
  serviceName: "ecommeureka"
  replicas: 1
  selector:
    matchLabels:
      app: ecommeureka
  template:
    metadata:
      labels:
        app: ecommeureka
    spec:
      containers:
        - name: ecommeureka
          image: jeffinjude/ecomm-eureka-server:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8761

---                  

apiVersion: v1
kind: Service
metadata:
  name: ecommeureka-lb
  labels:
    app: ecommeureka
spec:
  selector:
    app: ecommeureka
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30000
