apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-order-processing-app
  labels:
    app: ecomm-order-processing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : ecomm-order-processing-app
  template:
    metadata:
      labels:
        app: ecomm-order-processing-app
    spec:
      containers:
      - name: ecomm-order-processing-app
        image: jeffinjude/ecomm-order-processing:1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8092

---

kind: Service
apiVersion: v1
metadata:
  name:  ecomm-order-processing-svc
spec:
  selector:
    app:  ecomm-order-processing-app
  ports:
  - port:  8092
    targetPort:  8092
